---
- name: Listen for events on a webhook
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: backup all switches and upload to snow
      condition: event.payload.text is match("backup") and event.payload.text is search("all")
      action:
       run_playbook:
        name: backup_all.yml
        post_events: true

    - name: backup switch ceos2 and create snow incident
      condition: event.payload.text is match("backup") and event.payload.text is search("ceos2")
      action:
       run_playbook:
        name: backup_ceos2.yml
        post_events: true

    - name: backup switch ceos3 and create snow incident
      condition: event.payload.text is match("backup") and event.payload.text is search("ceos3")
      action:
       run_playbook:
        name: backup_ceos3.yml
        post_events: true

    - name: log ticket with config files
      condition: event.backup_done == "complete"
      action:
       run_playbook:
        name: snow_incident.yml

- name: Port State Event from Arista

  hosts: all
  sources:
   - ansible.eda.kafka:
       host: broker
       port: 9092
       topic: network

  rules:
   - name: Port is down
     condition: event.fields.admin_status == "DOWN"
     action:
       run_playbook:
        name: desired_port_state.yml

   - name: BGP change detected
     condition: event.fields.session_state == "IDLE"
     action:
       run_playbook:
        name: bgp_troubleshooting.yml
        post_events: true

   - name: Trouble shoooting finished
     condition: event.status == "done"
     action:
        run_playbook:
          name: bgp_status.yml